### ISSUE TITLE
Add embedded "Build Status" widgets.

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/OmniJ#102]
Jenkins can provide a build status widget for each job, but because I've configured Jenkins to only serve via `https://` _and we're using a self-signed SSL certificate_  the image embedding doesn't work correctly on Github.

You can see the issue below:
[![Build Status](https://ci.omni.foundation/buildStatus/icon?job=OmniJ)](https://ci.omni.foundation/job/OmniJ/)

@achamely, @dexX7  Any suggestions on how to configure NGINX to redirect to `https://` for all requests but this image?

**Comment by dexX7** [comment]
I'm not too familiar with this, but can you create an exception for `ci.omni.foundation/buildStatus/` (as seperate `location`, or sub project)?

**Comment by msgilligan** [comment]
I'm actually thinking about getting a free certificate using [Let's Encrypt](https://letsencrypt.org) -- that's probably the best solution.

**Comment by msgilligan** [comment]
We've had these for Github Actions for a while now.
