### ISSUE TITLE
Milestone 0.4 is targeting 0.0.9 but 0.0.9 is unusable within a couple of weeks

### ISSUE THREAD

**Issue by zathras-crypto** [OmniLayer/OmniJ#122]
Hey bud,

Just a quick note - I saw on the all hands doc that you were targeting 0.0.9 for your 0.4 milestone - I just wanted to make sure you were aware that 0.0.9 is unusable (and will automatically shutdown) after block 395000 (a couple of weeks time).

Thanks
Z

**Comment by msgilligan** [comment]
Thanks, Z.

Release 0.4 will work with 0.0.9 and 0.0.10. Release 0.5 will *require* 0.0.10.
