### ISSUE TITLE
Rebrand of the token MSC -> OMNI

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/OmniJ#123]
Rebrand the token (e.g. `CurrencyID.MSC` -> `CurrencyID.OMNI`) and related code.

We will try to keep backward compatibility with deprecation warnings, but that's not a top priority for release 0.5. (Doing a global replace of `MSC` to `OMNI` in client source code shouldn't be too hard.)

**Comment by msgilligan** [comment]
This is complete *and* old values are still present with deprecated warnings:

* Rename of CurrencyIDs: 7a340c267b2be68c2b2a232c6177f18f60297e09
* Rename of Ecosystems: 43a85f2073ddc090faafddb38bb822a6e16467b5
* Add old constants with `deprecated` flag: 660c896466bb7df0ff742eaa13484b138e542809

@dexX7 Is there anything else we should do for this issue before closing it out?

**Comment by dexX7** [comment]
Looks good to me!
