### ISSUE TITLE
Test log spammed since update to bitcoinj 0.14.1

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#127]
The log of the CI builds is spammed like this:

```
foundation.omni.test.rpc.activation.AllPairDExActivationSpec STANDARD_ERROR
    May 17, 2016 7:11:00 PM org.bitcoinj.core.Context <init>
    INFO: Creating bitcoinj 0.14.1 context.
    May 17, 2016 7:11:01 PM org.bitcoinj.core.Context <init>
    INFO: Creating bitcoinj 0.14.1 context.
foundation.omni.test.rpc.activation.GracePeriodSpec
...
```

See: https://travis-ci.org/OmniLayer/OmniJ/builds/130922885#L246 (and newer builds)

It looks like this started with the update to bitcoinj 0.14.1.

**Comment by msgilligan** [comment]
Yes, something changed in bitcoinj 0.14.1 -- I haven't figured out exactly what or how to fix it, yet.

**Comment by msgilligan** [comment]
I added `logging.properties` to both subprojects with `regTest` tasks. I also upgraded to Gradle 2.14.1-rc-1. Gradle 2.14 contained [a fix that we needed](https://docs.gradle.org/current/release-notes.html#tests-now-respect-java.util.logging.config.file-by-default).
