### ISSUE TITLE
Use generate instead of setgenerate

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#137]
The 0.13 based Omni Core currently forwards requests for `setgenerate`, but ultimately OmniJ should use the new RPC `generate`, to generate a block.

**Comment by msgilligan** [comment]
I thought I had already done this -- maybe I missed some cases? I'll double-check -- and I agree.

**Comment by dexX7** [comment]
Wait, maybe I missed the update. I haven't actually tested it without the forward.

**Comment by msgilligan** [comment]
There is still some cleanup around `generate` / `setgenerate` but I'm pretty sure `setgenerate` is no longer being used in any of the RegTests.

I just now made some further (final?) changes in this area:
* bitcoinj-addons: https://github.com/msgilligan/bitcoinj-addons/commit/50bc6101fb3c7a4383b320cf097cd8ef67d7e637
* OmniJ: https://github.com/OmniLayer/OmniJ/commit/ddda1a585271e1c6a48bcfb79425a9532791776d

**Comment by dexX7** [comment]
Looks good to me! Even without the forward (https://github.com/OmniLayer/omnicore/pull/440) the OmniJ tests pass.
