### ISSUE TITLE
How to build Class C transactions by Omnij

### ISSUE THREAD

**Issue by ruanqunfeng** [OmniLayer/OmniJ#147]

**Comment by ruanqunfeng** [comment]
@dexX7 Can you help me ?

**Comment by dexX7** [comment]
Hi @ruanqunfeng, currently there is no handy way to build class C transactions with OmniJ.

But then again, please see (3) of this post for some direction:

https://github.com/OmniLayer/omnicore/issues/664#issuecomment-400630510

**Comment by msgilligan** [comment]
This is a duplicate of #120
