### ISSUE TITLE
rpc Most of the time there is a timeout, occasionally you can connect

### ISSUE THREAD

**Issue by liuhuanhui** [OmniLayer/OmniJ#150]
### system
Linux usdt-server 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

### omnicored -version
Omni Core Daemon version v0.13.2.0-g5d5afbb37e81
Copyright (C) 2009-2017 The Bitcoin Core and Omni Core developers

Please contribute if you find Omni Core useful. Visit <http://omnilayer.org>
for further information about the software.
The source code is available from <https://github.com/OmniLayer/omnicore>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <http://www.opensource.org/licenses/mit-license.php>.

This product includes software developed by the OpenSSL Project for use in the
OpenSSL Toolkit <https://www.openssl.org/> and cryptographic software written
by Eric Young and UPnP software written by Thomas Bernard.

### In addition to the above problems, there are often the following situations when it is synchronized, is it normal?

![_20180813155908](https://user-images.githubusercontent.com/10370625/44019601-dcc8c5e0-9f11-11e8-922b-8d75e11cf77f.png)

**Comment by msgilligan** [comment]
Is this an issue with Omni Core or with OmniJ?

**Comment by dexX7** [comment]
Hi @liuhuanhui,

please try our newest release v0.3.1, which adds stability and performance to the initial parsing process.

That aside, while the client still synchronizes, the RPC interface can be unresponsive.
