### ISSUE TITLE
Unable to import maven

### ISSUE THREAD

**Issue by joenhon** [OmniLayer/OmniJ#151]
<dependency>
  <groupId>foundation.omni</groupId>
  <artifactId>omnij-rpc</artifactId>
  <version>0.5.5</version>
  <type>pom</type>
</dependency>
Library Maven: foundation.omni:omnij-rpc:0.5.6 has broken classes path:   C:\Users\Administrator\.m2\repository\foundation\omni\omnij-rpc\0.5.6\omnij-rpc-0.5.6.jar [Fix]

**Comment by msgilligan** [comment]
Do you have a sample/public repo that demonstrates this issue. I use Gradle for everything these days and the POM seems to be valid in Gradle.

**Comment by joenhon** [comment]
Thanks！

**Comment by msgilligan** [comment]
I've added a sample app (with a Maven build): https://github.com/OmniLayer/omnij-maven-sample
