### ISSUE TITLE
Sync speed very slow!

### ISSUE THREAD

**Issue by hungdung1326** [OmniLayer/OmniJ#155]
please help me...
i using RPC getinfo and response is:
{
"version": 130200,
"protocolversion": 70015,
"walletversion": 130000,
"balance": 0.00000000,
"blocks": 236506,
"timeoffset": 1,
"connections": 20,
"proxy": "",
"difficulty": 11187257.46136079,
"testnet": false,
"keypoololdest": 1536910386,
"keypoolsize": 100,
"paytxfee": 0.00000000,
"relayfee": 0.00001000,
"errors": ""
}
the connections to node of mine are 20 but sync speed is very slow.. Could anyone help me please... thank you so much!!

**Comment by msgilligan** [comment]
This doesn't sound like an OmniJ issue, but an overall Omni or Omni Core issue. Am I right?

**Comment by msgilligan** [comment]
You're cross-posting this issue into multiple projects: https://github.com/bitcoin/bitcoin/issues/14406
Closing.
