### ISSUE TITLE
Using bitcoinj's peerGroup to broadcast your omni transaction?

### ISSUE THREAD

**Issue by ddengster** [OmniLayer/OmniJ#156]
Hi, 

I'd like to ask whether its possible to build a transaction using omnij and then broadcasting it to the network of (likely) BTC nodes. Or if there's an option of a peergroup of Omni nodes so they can verify my broadcasted transactions.

Thanks

**Comment by msgilligan** [comment]
Omni transactions are valid Bitcoin transactions and may be broadcast to BTC nodes. You do not need a peergroup of Omni nodes.
