### ISSUE TITLE
Getting error while building jar

### ISSUE THREAD

**Issue by sj225** [OmniLayer/OmniJ#163]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'shadowJar' not found in project ':omnij-cli'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Can somebody help with this?  Want to use api's

**Comment by msgilligan** [comment]
Which branch/snapshot are you trying to build? Which Gradle command(s) are you using? The master branch builds fine on CI: https://ci.omni.foundation/job/OmniJ/399/console

Also you don't need to build OmniJ to use the API, you can just use the JARs: https://bintray.com/beta/#/omni/maven/omnij/0.5.8

**Comment by XBean1024** [comment]
> Which branch/snapshot are you trying to build? Which Gradle command(s) are you using? The master branch builds fine on CI: https://ci.omni.foundation/job/OmniJ/399/console
> 
> Also you don't need to build OmniJ to use the API, you can just use the JARs: https://bintray.com/beta/#/omni/maven/omnij/0.5.8
```
./gradlew build :omnij-cli:shadowJar
```
I have the same problem
```
Task 'shadowJar' not found in project ':omnij-cli'.
```

**Comment by XBean1024** [comment]
And I ended up using jar on jecnter

**Comment by XBean1024** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Task 'shadowJar' not found in project ':omnij-cli'.
> * Try:
>   Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> Can somebody help with this? Want to use api's

```

    compile 'foundation.omni:omnij-cli:0.5.8'
    compile 'foundation.omni:omnij-core:0.5.8'
    compile 'foundation.omni:omnij-dsl:0.5.8'
    compile 'foundation.omni:omnij-jsonrpc:0.5.8'
    compile 'foundation.omni:omnij-money:0.5.8'
    compile 'foundation.omni:omnij-rest-client:0.5.8'
```

**Comment by LenMotion** [comment]
I had the same problem. How did you solve it? please

**Comment by ckpenep** [comment]
I had the same problem. How can I resolve it? or how can I integrate it to my project? Your docs have little info about it

**Comment by msgilligan** [comment]
> And I ended up using jar on jcenter

@LenMotion @ckpenep 

The best way to get started is to use the **published JARs**.

Note that the published JARs are now on **GItLab** (**JCenter** has shut down)

 I have updated the **README** to provide more detailed instructions on how to use the published jars, see the section titled: [Including the OmniJ Maven Artifacts (JARs) in your build](https://github.com/OmniLayer/OmniJ#including-the-omnij-maven-artifacts-jars-in-your-build). There are subsections for both [Maven](https://github.com/OmniLayer/OmniJ#maven) and [Gradle](https://github.com/OmniLayer/OmniJ#gradle).
 
 I have also updated the [Building OmniJ](https://github.com/OmniLayer/OmniJ#building-omnij) section of the README. The `shadowJar` target has been removed and the README was out-of-date. (I wish I had noticed and fixed this earlier.)

**Comment by msgilligan** [comment]
Fixed in documentation, via: https://github.com/OmniLayer/OmniJ/commit/391d154fad8c436341743acc1b54a65e2073c4c9

**Comment by msgilligan** [comment]
Note also that I've added a sample app (with a Maven build): https://github.com/OmniLayer/omnij-maven-sample

**Comment by ckpenep** [comment]
I have created new Android project and added both dependencies:
maven { url 'https://gitlab.com/api/v4/projects/26583853/packages/maven' } - to the repositories section
and implementation "foundation.omni:omnij-core:0.5.18" to the dependencies section.  And after that I have an error:
Failed to resolve: foundation.omni:omnij-core:0.5.18
Can you check the implementation of this in your own project? What have I done wrong?

**Comment by ckpenep** [comment]
I resolved my broblem. Maybe someone it will be useful. I added this: 
 maven { url 'https://gitlab.com/api/v4/projects/26583853/packages/maven' } 
 to the settings.gradle and it launch

**Comment by msgilligan** [comment]
@ckpenep For Android projects you typically add the repositories to the project-level `build.gradle` and add the dependencies to the app module `build.gradle`. You shouldn't be adding either of those to `settings.gradle`, but if it works for you I guess that's ok.
