### ISSUE TITLE
General issues with the project or IDEA IntellJ

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#59]
Configured via default project structure I use "Oracle JDK 8" as project SDK and "8 - Lambdas, type annotations, etc."  as default project language level. `JAVA_HOME` is also properly defined.

1) Language level:

When cloning bitcoin-spock and creating a new project with "Check out from Version Control", and opening `/bitcoin-spock/build.gradle` as suggested, and using the default gradle wrapper, then the project language level switches to "6 - Override in interfaces".

![checkout](https://cloud.githubusercontent.com/assets/5836089/6751756/251ecca0-cf08-11e4-8327-d2d432068c7a.png)

![gradle](https://cloud.githubusercontent.com/assets/5836089/6751758/27048c1c-cf08-11e4-9d94-52145ae95564.png)

 As result an error is generated:

```java
~/Projects/Java/bitcoin-spock/omnij-core/src/main/java/foundation/omni/CurrencyID.java
    Error:Error:line (28)java: strings in switch are not supported in -source 1.6
  (use -source 7 or higher to enable strings in switch)
```

2) Cross references:

After resolving this by selecting a higher language level, and making the project, a bunch of errors is shown, related to the inability to resolve some classes:

```java
~/Projects/Java/bitcoin-spock/omnij-rpc/src/main/groovy/foundation/omni/consensus/ConsensusEntryPair.groovy
    Error:Error:Groovyc: @Immutable processor doesn't know how to handle field 'address' of type 'org.bitcoinj.core.Address' while compiling class foundation.omni.consensus.ConsensusEntryPair.
@Immutable classes only support properties with effectively immutable types including:
- Strings, primitive types, wrapper types, Class, BigInteger and BigDecimal, enums
- other @Immutable classes and known immutables (java.awt.Color, java.net.URI)
- Cloneable classes, collections, maps and arrays, and other classes with special handling (java.util.Date)
Other restrictions apply, please see the groovydoc for @Immutable for further details
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/chest/tmsc/CompareCoreChestSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.ChestConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/chest/tetherus/CompareCoreChestSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.ChestConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy
    Error:Error:line (5)Groovyc: unable to resolve class foundation.omni.rpc.OmniCLIClient
    Error:Error:line (6)Groovyc: unable to resolve class foundation.omni.rpc.OmniClientDelegate
    Error:Error:line (8)Groovyc: unable to resolve class foundation.omni.test.TestSupport
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/chest/msc/CompareCoreChestSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.ChestConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersSpec.groovy
    Error:Error:line (7)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
    Error:Error:line (6)Groovyc: unable to resolve class foundation.omni.consensus.ConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/omni_www/tetherus/CompareCoreOmniSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/enginedb/OmniEngineDBSmokeSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.DBConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/remote_core/msc/CompareCoreCoreSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/remote_core/tetherus/CompareCoreCoreSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/BaseMainNetSpec.groovy
    Error:Error:line (7)Groovyc: unable to resolve class foundation.omni.rpc.OmniCLIClient
    Error:Error:line (8)Groovyc: unable to resolve class foundation.omni.rpc.OmniClientDelegate
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/chest/maidsafecoin/CompareCoreChestSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.ChestConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/ChestServerSpec.groovy
    Error:Error:line (5)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
    Error:Error:line (4)Groovyc: unable to resolve class foundation.omni.consensus.ChestConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/omni_www/tmsc/CompareCoreOmniSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/OmniwalletServerSpec.groovy
    Error:Error:line (5)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/remote_core/tmsc/CompareCoreCoreSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/test/OmniClientDelegateSpec.groovy
    Error:Error:line (5)Groovyc: unable to resolve class foundation.omni.rpc.OmniClientDelegate
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/OmniCoreConsensusToolSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/omni_www/maidsafecoin/CompareCoreOmniSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/remote_core/maidsafecoin/CompareCoreCoreSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/BaseConsensusSpec.groovy
    Error:Error:line (7)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
    Error:Error:line (6)Groovyc: unable to resolve class foundation.omni.consensus.ConsensusFetcher
    Error:Error:line (5)Groovyc: unable to resolve class foundation.omni.consensus.ConsensusComparison
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/RPCSmokeTestSpec.groovy
    Error:Error:line (4)Groovyc: unable to resolve class foundation.omni.consensus.OmniCoreConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/integ/groovy/foundation/omni/test/consensus/omni_www/msc/CompareCoreOmniSpec.groovy
    Error:Error:line (3)Groovyc: unable to resolve class foundation.omni.consensus.OmniwalletConsensusTool
~/Projects/Java/bitcoin-spock/omnij-rpc/src/test/groovy/foundation/omni/consensus/SnapshotData.groovy
    Error:Error:line (19)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (20)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (23)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (20)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (21)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (22)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (23)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (24)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (26)Groovyc: unable to resolve class ConsensusSnapshot
    Error:Error:line (30)Groovyc: unable to resolve class ConsensusSnapshot
    Error:Error:line (34)Groovyc: unable to resolve class ConsensusSnapshot
    Error:Error:line (38)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (38)Groovyc: unable to resolve class ConsensusSnapshot
    Error:Error:line (39)Groovyc: unable to resolve class ConsensusSnapshot
~/Projects/Java/bitcoin-spock/omnij-rpc/src/test/groovy/foundation/omni/consensus/ConsensusEntryPairSpec.groovy
    Error:Error:line (17)Groovyc: unable to resolve class ConsensusEntryPair
    Error:Error:line (17)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (17)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (20)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (28)Groovyc: unable to resolve class ConsensusEntryPair
    Error:Error:line (28)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (28)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (39)Groovyc: unable to resolve class ConsensusEntry
    Error:Error:line (40)Groovyc: unable to resolve class ConsensusEntry
~/Projects/Java/bitcoin-spock/omnij-rpc/src/test/groovy/foundation/omni/consensus/ConsensusSnapshotSpec.groovy
    Error:Error:line (13)Groovyc: unable to resolve class ConsensusSnapshot
    Error:Error:line (25)Groovyc: unable to resolve class ConsensusSnapshot
~/Projects/Java/bitcoin-spock/omnij-rpc/src/test/groovy/foundation/omni/consensus/DataPipeSpec.groovy
    Error:Error:line (11)Groovyc: unable to resolve class ConsensusComparison
    Error:Error:line (12)Groovyc: unable to resolve class ConsensusComparison
    Error:Error:line (11)Groovyc: unable to resolve class ConsensusComparison
    Error:Error:line (12)Groovyc: unable to resolve class ConsensusComparison
~/Projects/Java/bitcoin-spock/omnij-rpc/src/test/groovy/foundation/omni/consensus/ConsensusComparisonSpec.groovy
    Error:Error:line (9)Groovyc: unable to resolve class ConsensusComparison
    Error:Error:line (9)Groovyc: unable to resolve class ConsensusComparison
```

**Comment by msgilligan** [comment]
Regarding language level:

The correct language level should be `1.7` for the current code, although we've been avoiding `<>` because it breaks GroovyDoc.

Perhaps better usage of the Gradle `idea` plugin can solve this problem. We should also probably upgrade to IntelliJ 14.1 EAP.

To be honest, I haven't really mastered the Gradle -> IntelliJ import process and spend too much time futzing around with it. I need to learn how to do this better and automate/document it.

**Comment by msgilligan** [comment]
You could try the following:

1. close project
1. `gradle cleanIdea idea`
1. re-import

**Comment by msgilligan** [comment]
The problem with `foundation.omni.consensus.ConsensusEntryPair` is that it depends upon a change that is in bitcoinj master that has not been released. This is a change to `Address` that I submitted upstream to make it `Cloneable` and `Comparable` which allows some of the consensus types to be `@Immutable` and also allows `Address` to be used as a key in a `Map`.

Prior to the multi-project refactor I had checked a locally-built copy of bitcoinj into `${projectDir}/lib/bitcoinj-core-0.13-SNAPSHOT.jar`. In the multi project build, `bitcoin-rpc` and `omnij-core` use the released version of bitcoinj and the custom built version is in `${projector}/omnij-rpc/lib` `${projectDir}/lib/bitcoinj-core-0.13-SNAPSHOT.jar` and is only used for that subproject.

Hopefully running `gradle cleanIdea idea` and reimporting the project will fix this, too.

**Comment by dexX7** [comment]
I tested `gradlew cleanIdea idea` earlier without success, but I switched to EAP, reimported the project and used JDK 1.7 instead of 1.8, and unfortunally the error is still present.

**Comment by msgilligan** [comment]
I saw both of those problems and made both of the go away, but I don't remember exactly what I did.

You still have both errors?

**Comment by dexX7** [comment]
The first one can be resolved by manually changing the language level, the second one about the missing classes is still there. That being said, this is an IntelliJ issue, and using the gradle tasks works fine.

**Comment by msgilligan** [comment]
Actually, I still have the second problem. I've been using IntelliJ to edit and test `omnij-core`, but not `omnij-rpc`, apparently.

**Comment by msgilligan** [comment]
OK, I just made commit be146430b4f9472e243b41fd3d74258c662fe2ea which fixes the problem for me. It uses the local build of bitcoinj-core for all subprojects. Let me know if it helps.

**Comment by dexX7** [comment]
Ah I see, I'm going to test this tomorrow and report back, thanks in advance for looking into it! :)

**Comment by dexX7** [comment]
Pretty close!

Route 1)

- guided checkout/import via git as described in the first post

Route 2)

- git clone bitcoin-spock
- gradlew idea
- open project with IntelliJ Idea
- import gradle project as suggested

In both cases the language level related error is present, and resetting to level 6, but after manually changing it in the project structure settings, building via both routes was successful.

Tested with current master (https://github.com/msgilligan/bitcoin-spock/commit/be146430b4f9472e243b41fd3d74258c662fe2ea) and IntelliJ IDEA 14.1 141.176.5 (released March 20th, EAP, Community Edition).

So your commit indeed solved one half of this issue. :)

**Comment by dexX7** [comment]
Two warnings I recently saw while testing:
```
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: ~/Projects/Java/bitcoin-spock/omnij-rpc/src/main/java/foundation/omni/rpc/OmniClient.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
```

**Comment by msgilligan** [comment]
I believe that is caused because the JDK you are using is Java 8. If you install JDK 7 and init your shell environment with

    export JAVA_HOME=`/usr/libexec/java_home -v1.7`

it should go away.

**Comment by dexX7** [comment]
Yup, this is the case.

Regarding the unchecked warning: if I recall correctly, the warning was suppressed, where appropriate, with:
```java
@SuppressWarnings("unchecked")
```

But when searching for that line, I didn't find any matches. Was this removed by any chance, and if so, why? Should I add it back?

**Comment by msgilligan** [comment]
I removed a bunch of them in commit 3a25bcca5561eeac5dce356a5acef942a2756f80 because they seemed to be no longer necessary (at least according to IntelliJ)

**Comment by msgilligan** [comment]
OK, added `-Xlint:unchecked` to the compile options. (Any reason that shouldn't be left in permanently?) and I probably should check my IntelliJ settings to make sure the same warnings are displayed while editing. I would prefer a way of making the warnings go away without suppressing them, but maybe (as before?) there is no good way of doing that.

One thing that I'd like to investigate at some time in the future is making better use of Jackson JSON mapping which could change (and simplify) the code quite a bit.

**Comment by msgilligan** [comment]
I think I found a way to suppress the casting warnings for the send() method. Working on it now...

**Comment by dexX7** [comment]
Interesting, this didn't suppress the warnings, but actually made them more precise:
```gradle
compileJava {
    options.compilerArgs << '-Xlint:unchecked'
}
```
With `'-Xlint:unchecked'`:
https://gist.githubusercontent.com/dexX7/f762a19b07a0d35001ad/raw/

Without `'-Xlint:unchecked'`:
https://gist.githubusercontent.com/dexX7/ab822a36e0b817b32d5e/raw/

Tests started from within the IDE, and not as gradle task.

**Comment by msgilligan** [comment]
Yes, that's what I expected -- I had used that setting before.

**Comment by msgilligan** [comment]
OK, this fix 7c34639b1b02b896a96a52d1a1a952c5214cb0b1 looks like the best way to handle these warnings.

**Comment by dexX7** [comment]
Very elegant solution! I like it and it works.

**Comment by dexX7** [comment]
More issues: it started with missing `javax.money`, after which I refreshed everything a few times, used `cleanIdea idea` inbetween, and opened the project once again:

![dependencies](https://cloud.githubusercontent.com/assets/5836089/7103272/c63efba2-e09f-11e4-8e9e-6535f242266f.png)

**Comment by msgilligan** [comment]
I have the repo error in my settings, too. But IntelliJ was able to find the JAR, so building and testing work properly.

**Comment by dexX7** [comment]
Since https://github.com/OmniLayer/OmniJ/commit/b04365733a7414f97a0d84cca54fff592bef58b6 it's no longer possible to run tests directly from the IDE?
```
com.msgilligan.bitcoin.rpc.JsonRPCStatusException: Authorization Required
```

```groovy
class SystemPropertiesSpec extends Specification {

    def "The RPC credentials are defined"() {
        given:
        def rpcTestUser = System.getProperty("omni.test.rpcTestUser")
        def rpcTestPassword = System.getProperty("omni.test.rpcTestPassword")

        expect:
        rpcTestUser != null
        rpcTestPassword != null
    }

}
```

**Comment by msgilligan** [comment]
Oh, maybe. I guess CI integration tests should also be run in the IDE to make sure I didn't break it ;).

Short term workaround is to hardcode the values back in the TestServers classes. Longer term solution is to figure out how to configure IDE to initialize system properties. We should probably learn how to better use the 'idea' plugin for configuration.

Note that IntelliJ does let you run the tests via Gradle (which is clunkier than running them directly) which should find the systemProperties values.

Send me a pull request for the `SystemPropertiesSpec`, please. ;)

**Comment by dexX7** [comment]
> Short term workaround is to hardcode the values back in the TestServers classes.

Yup, that works.

> Note that IntelliJ does let you run the tests via Gradle

I'm not exactly sure how (expect creating new tasks manually), but I assume this is less convenient than two clicks to run or debug a test.

> Send me a pull request for the SystemPropertiesSpec, please. ;)

Haha, feel free to pick it up. - I have no idea where to place it, i.e. which subproject or package. :)

**Comment by msgilligan** [comment]
I find that IntelliJ gives me two icons when I right click on a test spec, one that is a Gradle icon and the other that looks more like a red/green unit test UI. The red/green thingy runs directly in the IDE and the Gradle icon runs them through Gradle. Once you make a choice it becomes the default. I don't know how to change that choice once you've made it.

Maybe the check in SystemPropertiesSpec should be in one or more of the base classes as an assert?

**Comment by dexX7** [comment]
You were referring to this, right?

![run_gradle](https://cloud.githubusercontent.com/assets/5836089/7216102/b7403352-e5f2-11e4-906c-606cd74a1ad0.png)

I can see in the console view how the test is executed:
```
Testing started at 17:46 ...
17:46:26: Executing external tasks 'cleanTest test --tests "foundation.omni.test.test.SystemPropertiesSpec.The RPC credentials are defined"'...
...
```

Further, when I try to run this test via a terminal (though I'm not sure, if I'm doing it right), the test fails:
```shell
$ ./gradlew :omnij-rpc:cleanTest :omnij-rpc:test --tests "foundation.omni.test.test.SystemPropertiesSpec.The RPC credentials are defined"
```

![rpc_creds](https://cloud.githubusercontent.com/assets/5836089/7216115/92b276de-e5f3-11e4-9685-9856d9dce240.png)

**Comment by dexX7** [comment]
The following did the trick, but I'm not sure, if the scope is now too broad:
```diff
$ git diff
diff --git a/omnij-rpc/build.gradle b/omnij-rpc/build.gradle
index c94429f..a8e5cdf 100644
--- a/omnij-rpc/build.gradle
+++ b/omnij-rpc/build.gradle
@@ -46,6 +46,9 @@ shadowJar {
 }
 
 test {
+    systemProperties ([ "omni.test.rpcTestUser": rpcTestUser,
+                        "omni.test.rpcTestPassword": rpcTestPassword,
+    ])
     // show standard out and standard error of the test JVM(s) on the console
     testLogging.showStandardStreams = true
 }
@@ -114,9 +117,6 @@ task regTest(type: Test) {
     }
 
     systemProperty 'regtest', true
-    systemProperties ([ "omni.test.rpcTestUser": rpcTestUser,
-                        "omni.test.rpcTestPassword": rpcTestPassword,
-    ])
     include 'foundation/omni/test/rpc/**', 'foundation/omni/test/tx/**'
 }
```

**Comment by msgilligan** [comment]
The default Gradle `test` task is supposed to run "true" unit tests (i.e. test that don't use networking or talk to any servers and that run *quickly*) for the `omnij-rpc` module, there currently are only [these files](https://github.com/OmniLayer/OmniJ/tree/master/omnij-rpc/src/test/groovy/foundation/omni/consensus)

It appears that IntelliJ doesn't know that the tests in the `integ` folder are associated with the `regTest` (integration) test task. There may be a way to tell IntelliJ about the association and that would solve our problem.

The unit tests don't need the `rpcTestUser` and `rpcTestPassword` settings, but they shouldn't hurt anything either. So you're above change seems like a quick and easy solution.

**Comment by dexX7** [comment]
https://github.com/OmniLayer/OmniJ/commit/d0e623befd1faeec5963279974f9c48576b3de2e works very well, but maybe there could be an explicit task to run tests as regtests, like:

```gradle
task runRegTest(type: Test) {
    testLogging.showStandardStreams = true

    beforeTest { descriptor ->
        logger.lifecycle(descriptor.getName())
    }

    systemProperty 'regtest', true
    systemProperties( ["omni.test.rpcTestUser"    : rpcTestUser,
                       "omni.test.rpcTestPassword": rpcTestPassword,
    ])
}
```

I don't really see much need for it at the moment though, but it could become more useful, when mixed with other user input, such as the RPC credentials for example, at some point later.

**Comment by msgilligan** [comment]
There is an explicit task to run tests as regtests, it's called `regTest` and is [here](https://github.com/OmniLayer/OmniJ/blob/master/omnij-rpc/build.gradle#L102).

**Comment by dexX7** [comment]
> There is an explicit task to run tests as regtests, it's called regTest and is here.

Aahh.. for some reason I never tested it, and I didn't know it's possible to run a single test via `regTest`.

**Comment by dexX7** [comment]
Another one (sort of) related to the RPC credentials, when starting clean, and directly using `regTest`:
```
~/Projects/Java/OmniJ$ ./gradlew :omnij-rpc:regTest
:bitcoin-rpc:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:bitcoin-rpc:compileGroovy
:bitcoin-rpc:processResources UP-TO-DATE
:bitcoin-rpc:classes
:bitcoin-rpc:jar
:omnij-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:omnij-core:compileGroovy UP-TO-DATE
:omnij-core:processResources UP-TO-DATE
:omnij-core:classes
:omnij-core:jar
:omnij-rpc:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
~/Projects/Java/OmniJ/omnij-rpc/src/main/java/foundation/omni/rpc/test/TestServers.java:11: error: package com.msgilligan.bitcoin.rpc.test does not exist
public class TestServers extends com.msgilligan.bitcoin.rpc.test.TestServers {
```

**Comment by msgilligan** [comment]
I'm not sure what's going on in the output above, @dexX7. If you look at the output you can see that it is building the required subproject first. Note also that the problem is a compile-time error not run-time.

You can see that `bitcoin-rpc:compileJava` is the first task run, and that `:omnij-rpc:compileJava` is the task running when it fails.

I can't reproduce it on my system. But I should mention that 9 days ago, I found (for some reason) that I had to add this: 9c0287f5dbc9d0d0c0dd9ed5fe975631def1ef08

**Comment by dexX7** [comment]
@msgilligan: thanks. I think this was my mistake. I didn't entirely start from zero, but updated my local copy of OmniJ, and then started `:omnij-rpc:regTest`. `clean` helped in this case, and there is indeed no issue, when starting with a pristine state (e.g. after cloning the repo).

**Comment by msgilligan** [comment]
Good to hear.

What's the next step in resolving this issue? I think it is learning how to best use the Gradle IDEA plugin to initialize the IDEA project file correctly, though I'm not sure that approach will solve the remaining issues.

**Comment by dexX7** [comment]
> What's the next step in resolving this issue?

Do we have a target for this issue? One is probably related to project imports/creation.

Generally, I think this thread could serve for "general issues, which don't deserve new issue". This is sort of what I had in mind, when I renamed it. Most of those are related to IntelliJ IDEA though.. :)

**Comment by msgilligan** [comment]
I just like to close issues when possible. I'm trying to keep open issues down to a single page, which seems feasible for this project.

Yeah, if we can document and automate the import process that might solve this issues or, at the very least, make whatever issues we are having reproducible by multiple people so we can better investigate and solve them.

**Comment by msgilligan** [comment]
@dexX7 I added these settings which should help with the language level: c07cadc2dbd463106b7c494bdddeac968ea7ebf8

I stumbled across them while looking for something else and didn't have time to test them with a project import into IDEA, but they should do the trick.

**Comment by dexX7** [comment]
Project import with current master works as expected. Well done!
