### ISSUE TITLE
How to handle checked transaction creation via Omni Core

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#62]
I'm wondering, how we should handle tests in the future, given that transaction creation for all transaction types is going to be available soon in Omni Core.

Currently, for example for the DEx spec, raw transactions are created and pushed via `"sendrawtx_MP"`, which bypasses all checks. In contrast, the new `"sendXXX"` RPC calls of Omni Core check certain requirements, e.g. whether the caller has a sufficient balance, or if a property indeed exists.

Now we probably want to test both cases:

- bypass the RPC checks, to test the actual transaction processing
- but also test the RPC interface and it's checks

With that in mind, I created the STO tests to run two times, once using the RPC call ["sendtoowners_MP"](https://github.com/msgilligan/bitcoin-spock/blob/aeb30ff4d8789cfc45a1c05edce1998bfe40be17/omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanSpec.groovy#L382-L398), and a second time by using ["sendrawtx_MP"](https://github.com/msgilligan/bitcoin-spock/blob/aeb30ff4d8789cfc45a1c05edce1998bfe40be17/omnij-rpc/src/integ/groovy/foundation/omni/test/rpc/sto/SendToOwnersTestPlanRawSpec.groovy#L14-L28).

The STO testing is very specific though, and I'm wondering, if there should be a more generalized solution in the future, and how this could look like.

**Comment by msgilligan** [comment]
I agree there should be a more generalized solution. There are at least 3 ways to create and send a Bitcoin transaction:

1. RPC call, like `SendFrom` or `SendToAddress`. (These require that wallet support be enabled)
1.  `SendRawTransaction`.
1. Created client-side by the tests (e.g. using bitcoinj) and sent via P2P.

For Omni transactions, there are at least 4 methods:

1. Omni RPC call, e.g. `send_MP`
1.  `sendrawtx_MP`
1. `SendRawTransaction`
1. P2P

**Comment by dexX7** [comment]
Just some brainstorming: currently there is the `OmniClient`, which is used by the `OmniCLIClient`, which is part of the `OmniClientDelegate`, which is made available to the tests. There could be another layer inbetween, differentiating between a `SendRawTxsOmniClient`, `SendCheckedTxsViaRPCOmniClient` or `SomeOtherOmniClient`. Or ideally, instead of switching between different `OmniClient`, the transaction creation should probably be a modular part on it's own, similar to the `OmniTxBuilder`.

From a practial perspective, and I'm just focusing on those two routes, transactions can either be created via:

- `sendXXX`, which throws an exception, if the requirements are not met
- raw transaction creation, broadcasted by `sendrawtx_MP`, which can be confirmed by using `gettransaction_MP` and checking the `valid` field

Where I'm getting is something like this:
```groovy

interface TransactionSender
{
    Boolean send(Address address, CurrencyID currency, BigDecimal amount)
}

class CheckedTransactionSender implements TransactionSender
{
    Boolean send(Address address, CurrencyID currency, BigDecimal amount) {
        try {
            rpcclient.send_MP(address, currency, amount)
        } catch (Exception) {
            return false
        }
        rpcclient.setgenerate(true, 1)
        return true
    }
}

class UncheckedTransactionSender implements TransactionSender
{
    Boolean send(Address address, CurrencyID currency, BigDecimal amount) {
        def txHex = txbuilder.createSimpleSendHex(address, currency, amount)
        def txHash = rpcclient.sendrawtx_MP(address, txHex)
        rpcclient.setgenerate(true, 1)
        def txConfirmed = rpcclient.gettransaction_MP(txHash)
        return txConfirmed['valid']
    }
}
```

**Comment by dexX7** [comment]
Recently I pushed https://github.com/OmniLayer/omnicore/pull/55, and at least the non-state-dependent checks can be tested via unit tests.

Given that, I tend to think we should primarily test unchecked transactions, and bypass the RPC checks.

**Comment by dexX7** [comment]
There is currently no specific item to discuss/to do, so I'm going to close this.
