### ISSUE TITLE
Print current test to the log

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#68]
When executing the Gradle tasks, for example `./gradlew :omnij-rpc:regTest`, then the output is rather cryptic and non-telling:

```
> ...
> Building 94% > :omnij-rpc:regTest > 27 tests completedfoundation.omni.test.rpc.misc.ClientConfigurationAndFundingSpec STANDARD_ERROR
> Building 94% > :omnij-rpc:regTest > 27 tests completed    Apr 14, 2015 10:33:10 PM org.slf4j.Logger$info call
> Building 94% > :omnij-rpc:regTest > 27 tests completed    INFO: Waiting for server...
> Building 94% > :omnij-rpc:regTest > 27 tests completed    Waiting for server RPC ready:
> Building 94% > :omnij-rpc:regTest > 27 tests completed
> Building 94% > :omnij-rpc:regTest > 27 tests completed    RPC Ready.
> Building 94% > :omnij-rpc:regTest > 27 tests completed8 tests completed9 tests completed30 tests completed1 tests completed2 tests completed3 tests completed4 tests completed5 tests completed6 tests completed7 tests completed8 tests completed9 tests completed40 tests completed1 tests completed
> Building 94% > :omnij-rpc:regTest > 41 tests completedfoundation.omni.test.rpc.smartproperty.SmartPropertySpec STANDARD_ERROR
> Building 94% > :omnij-rpc:regTest > 41 tests completed    Apr 14, 2015 10:33:12 PM org.slf4j.Logger$info call
> Building 94% > :omnij-rpc:regTest > 41 tests completed    INFO: Waiting for server...
> ...
```

It would certainly be possible to manually add a log entry for each test, but I was wondering, if there is a more Groovy way to report the current test, which is executed?

**Comment by msgilligan** [comment]
Looking at the documentation for the Gradle [Test Task](http://gradle.org/docs/current/dsl/org.gradle.api.tasks.testing.Test.html), I think Adding the following code to the `test` closure in one or more of the `build.gradle` files should do it:

    // listen to events in the test execution lifecycle
    beforeTest { descriptor ->
        logger.lifecycle("Running test: " + descriptor)
    }

I think we should add this for the integration tests, but not the unit tests (which run quickly and more reliably and don't really need the verbosity.) Sound good?

**Comment by msgilligan** [comment]
OK, this should enable it for the two RegTest tests. Unit tests would be too verbose and so would the consigns check (because it would output for thousands of `@Unroll`ed address consensus checks.)

**Comment by dexX7** [comment]
Haha, you have a great timing. I'm currently playing with it. It's nice, thanks!

In my opinion the following lines are not really relevant, and I mostly wouldn't care about the RPC status, unless it's an exceptional state:

> Waiting for server RPC ready:
> 
> RPC Ready.

So just to give it a try, I tested printing the test suite and test title:
<pre>
<b>foundation.omni.test.rpc.basic.SendRawTransactionSpec</b>
    Create raw transaction with reference address
    Create raw transaction without reference address
<b>foundation.omni.test.rpc.basic.OmniSpec</b>
    Implement getbalance_MP
    Return Master Core version field using getinfo_MP
<b>foundation.omni.test.rpc.dex.DexSpec</b>
    A new sell offer can be created with Action = 1 (New)
    An accepted currency identifier for sell offers is CurrencyID:1
    An accepted currency identifier for sell offers is CurrencyID:2
    Offering more tokens than available puts up an offer with the available amount
    ...
</pre>

It probably comes down to the context though: while it's nice to watch the tests step forward one by one, with a style like above, it would probably be less useful, if one doesn't watch "live", and test reports are generated anyway. And as you already mentioned, it's an overall for consensus tests.

```diff
diff --git a/bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java b/bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
index 809056f..11a6e4a 100644
--- a/bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
+++ b/bitcoin-rpc/src/main/java/com/msgilligan/bitcoin/rpc/BitcoinClient.java
@@ -49 +49 @@ public class BitcoinClient extends RPCClient {
-        System.err.println("Waiting for server RPC ready:");
+        log.debug("Waiting for server RPC ready:");
@@ -57 +57 @@ public class BitcoinClient extends RPCClient {
-                    System.err.println("\nRPC Ready.");
+                    log.debug("\nRPC Ready.");
diff --git a/omnij-rpc/build.gradle b/omnij-rpc/build.gradle
index 7adbe47..34f52e6 100644
--- a/omnij-rpc/build.gradle
+++ b/omnij-rpc/build.gradle
@@ -107,0 +108,8 @@ task regTest(type: Test) {
+    beforeSuite { descriptor ->
+        if (descriptor.getClassName() != null) {
+            logger.lifecycle("\033[1m" + descriptor.getName() + "\033[0m")
+        }
+    }
+    beforeTest { descriptor ->
+        logger.lifecycle("    " + descriptor.getName())
+    }
diff --git a/omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy b/omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy
index 9c6f4e5..828cc3a 100644
--- a/omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy
+++ b/omnij-rpc/src/integ/groovy/foundation/omni/BaseRegTestSpec.groovy
@@ -26 +26 @@ class BaseRegTestSpec extends Specification implements OmniClientDelegate, OmniT
-        log.info "Waiting for server..."
+        log.debug "Waiting for server..."
```

**Comment by msgilligan** [comment]
That's some nice test formatting above! I like it.

In the early days of getting this stuff working -- especially on Jenkins -- those RPC Ready messages were really important for debugging. Now that it works reliably, much less so. 0.10.0 with earlier RPC responses on startup will also make things a lot nicer.

Can you send your changes as a PR?

**Comment by dexX7** [comment]
When running `bitcoin-rpc:regTest`, then there is still some other output, and it seems it is mostly related to BitcoinJ. Not an issue for me though. :)

**Comment by msgilligan** [comment]
`BriefLogFormatter.initWithSilentBitcoinJ()`: 403c7088fc83f96f69325290fb2bfe86611cbd42

**Comment by dexX7** [comment]
Awesome. :)
