### ISSUE TITLE
List this repository on OmniLayer.org

### ISSUE THREAD

**Issue by msgilligan** [OmniLayer/OmniJ#71]
The [OmniLayer.org](http://www.omnilayer.org) site has a *Repositories* section that should list *OmniJ*.

**Comment by dexX7** [comment]
I agree, and I was asking for an update of the website here as well: https://github.com/mastercoin-MSC/mastercore/issues/306

**Comment by msgilligan** [comment]
Shouldn't the source for [OmniLayer.org](http://www.omnilayer.org) be on Github so we can submit pull requests to update it?
@marv-engine @achamely @CraigSellars

**Comment by achamely** [comment]
@msgilligan the hosting site we use for OmniLayer.org is a WYSIWYG editor (wix.com). The source is basically the site as it exists right now. But yes, this should be added to the repo list on the site as well

**Comment by achamely** [comment]
@msgilligan updated and added to omnilayer.org  .
