### ISSUE TITLE
Console output of :omnij-rpc:regTest

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#79]
Hey @msgilligan,

OmniJ's RPC tests are now executed via Travis CI for Omni Core, but for some reason the standard output of `:omnij-rpc:regTest` is pretty messy, and differs from what I see locally:

- https://travis-ci.org/OmniLayer/omnicore/jobs/62741266#L3970-L4096

Do you know why, by any chance? :)

**Comment by dexX7** [comment]
https://issues.gradle.org/browse/GRADLE-1147 hinted a fix.

The following resolves the issue:
```shell
$ ./gradlew --console plain :omnij-rpc:regTest
```

**Comment by msgilligan** [comment]
You might want to try the `--console=plain` [command-line option](http://gradle.org/docs/current/userguide/gradle_command_line.html) of Gradle.

**Comment by msgilligan** [comment]
Looks like you found it already. :)

**Comment by dexX7** [comment]
Thanks a lot nevertheless! :)
