### ISSUE TITLE
Coin selection and allowed input types

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#85]
Unfortunally this is a very annoying issue, and I'm not sure where it's coming from.

The issue I'm referring to was already outlined in #44, but I assumed it somehow wasn't an issue anymore, after we restructured the funding methods:

> Assuming we start fresh and generate a block with setgenerate true 1, and then using getnewaddress, then the address is returned that received the generated coins. When getnewaddress is used before generating a block, then it looks like it's another address.

The behavior might not be exactly as described, and it's unclear to me how and why it happens.

When I start the regtests locally on this machine, the first test fails:
```
foundation.omni.test.rpc.reorgs.SendToOwnersReorgSpec
    After invalidating a send to owners transaction, the transaction is invalid

foundation.omni.test.rpc.reorgs.SendToOwnersReorgSpec > After invalidating a send to owners transaction, the transaction is invalid FAILED
    org.spockframework.runtime.ConditionNotSatisfiedError at SendToOwnersReorgSpec.groovy:21
```

This is not, because the test actually fails, but due to the rejection on a protocol level, of the inputs, which were selected to create the funding transaction.

The underlying issue is that using coinbase coins for Omni transactions aren't allowed, and somehow they are used for the funding transactions nevertheless.

To solve this issue, the funding logic needs to be refined further.

Given that OmniJ now uses Omni Core 0.0.10 we may think about alternatives though. For example, it may be thinkable to have a `"filterunspent"` RPC in Omni Core, to filter a set of unspent outputs, and select only those, which qualify as input for Omni transactions. Such a command might be useful for anyone, who uses Omni Core to create raw Omni Core transactions.

@msgilligan: What do you think?

**Comment by msgilligan** [comment]
> using coinbase coins for Omni transactions [isn't] allowed

I don't think I was aware of this rule. What is the reason for it?

At this point, I think it is OK to focus on Omni Core 0.0.10 for all testing code on the `master` branch of OmniJ. However, we should still (try to) support 0.0.9 in the `omnij-core` module until 0.0.10 is released.

**Comment by dexX7** [comment]
> I don't think I was aware of this rule. What is the reason for it?

That's a great question for probably @CraigSellars and @zathras-crypto.

Right now, any transaction input, which is not of type pay-to-pubkey-hash or pay-to-script-hash, invalidates the whole transaction. This includes bare multisig and pay-to-pubkey (which is used for coinbase transactions).

I think initially some kind of restriction was required to prevent that tokens are associated with something that may lead to an unexpected outcome. Let's assume tokens are associated with a 3-of-3 bare multisig input, then who might be considered as "sender"?

**Comment by zathras-crypto** [comment]
> I think initially some kind of restriction was required to prevent that tokens are associated with something that may lead to an unexpected outcome. Let's assume tokens are associated with a 3-of-3 bare multisig input, then who might be considered as "sender"?

This, in a nutshell.  

Especially in the early days when we had several competing implementations the key to keeping things "in consensus" was to minimize the surface for differences.  So rather than an "allow everything and block problems" we chose a "block everything and only allow what we need" kind of approach.  This way there is less dealing with unexpected outcomes.

**Comment by dexX7** [comment]
An upstream issue pointed me in the right direction, as this behavior was noticed by other regtest testers:

---

Somewhere in Bitcoin Core 0.9 the mining code was changed, and the key used for newly generated blocks was no longer removed from the keypool. This has performance implications, because until then a new key was generated, when mining regtest blocks. However, this has a significant downside: when mining blocks in regtest mode, and then getting a new key via `"getnewaddress"`, the new key may not be empty, but already received coins.

This is very undesired, and directly messes with some RPC tests, depending on the order of how they are exectued. The change is safe, and simply restores earlier behavior of Bitcoin Core.

I've benchmarked it's impact, and in practise it's performance impliciations are acceptable in my opinion, and the delay is within the range of a few seconds (from 2:00 to 2:10 min on my machine).

---

To reproduce in regtest mode, starting from scratch:
```shell
./src/bitcoin-cli "generate" 101
[
  # block hashes
]
./src/bitcoin-cli "listunspent"
[
  {
    "txid": "b148b7d13c3351875d070d0567855bce47fcc797b3504247c4fcd68d902523ab",
    "vout": 0,
    "address": "mu1ZwmfRH4HHowDrrjSTsqSfMKLBeZkn2a",
    "scriptPubKey": "2103ad57ff9cd560507938698630455ab926b070add217a3b30aead57cd578b935feac",
    "amount": 50.00000000,
    "confirmations": 101,
    "spendable": true
  }
]
./src/bitcoin-cli "getnewaddress"   # ... or "getrawchangeaddress"
mu1ZwmfRH4HHowDrrjSTsqSfMKLBeZkn2a  # the new address isn't empty, but has 50.0 BTC
```

Additional coins will be mined to that address, too, if `"generate"` is used again.
