### ISSUE TITLE
Rename artifact files and scripts from "bitcoin*" to "omnicore*"

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#88]
With https://github.com/OmniLayer/omnicore/pull/91 the relevant file names for OmniJ change as follows:
```
- src/bitcoind          -> src/omnicored
- src/bitcoin-cli       -> src/omnicore-cli
- src/test/test_bitcoin -> src/test/test_omnicore
```

**Comment by msgilligan** [comment]
Thanks, @dexX7 . When should we make this change?

**Comment by dexX7** [comment]
I'd like to wait for @zathras-crypto ACK, and then I'm ready when you are. :)

**Comment by dexX7** [comment]
@msgilligan: we are ready. Should we schedule a specific time to merge, or can I go ahead and merge https://github.com/OmniLayer/omnicore/pull/91?

**Comment by msgilligan** [comment]
If you're around now, go ahead and do it. Some tests will fail, but I'll fix them and run them again.

**Comment by dexX7** [comment]
Ah perfect, give me a minute.

**Comment by dexX7** [comment]
Done. :)

**Comment by msgilligan** [comment]
OmniJ changes are done: 790757073aa3628684813938f88ed24ad335849b

I've also updated the **Files to Archive** and **Execute Shell Command** settings of the `omnicore-integration` job on [ci.omni.foundation](https://ci.omni.foundation).

**Comment by dexX7** [comment]
Awesome. Looks like it went smooth. :)
