### ISSUE TITLE
Timeout consensus tests after n hours

### ISSUE THREAD

**Issue by dexX7** [OmniLayer/OmniJ#91]
It looks like the following build stalled:

https://ci.omni.foundation/job/omni-mainnet-consensus/97/console

Speaking of, could you please assign me a new user on the CI server? My old login isn't working anymore (probably after the 0.0.10 upgrade).

**Comment by msgilligan** [comment]
Hi @dexX7 , sorry of not responding sooner. If you create an account on the [signup page](https://ci.omni.foundation/signup) I can add permissions to it so you can start/stop jobs, etc.

**Comment by dexX7** [comment]
Thanks! I registred the user "dexx".

**Comment by dexX7** [comment]
The issue was resolved: the stalled build was stopped.
